### ISSUE TITLE
Integrate ensembling into AutoML

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#1130]
Epic design doc here: https://alteryx.quip.com/wcJbAoWJVpAN/Ensembling-Design-Document

This issue also tracks running and writing up perf tests before merging.

**Comment by dsherry** [comment]
Discussed perf test results with @angela97lin . Looking good!

Running into #1126, now that we're using `TrainingValidationSplit` to compute the ensemble scores in automl (instead of CV, since the ensembler does CV under the hood). Options: 1) fix the bug, 2) use CV instead of TV, 3) add `reset_index` workaround which worked or #1126.

**Next steps**
* Update which pipelines/parameters we pass to the stacked ensembler. I put a sketch on branch `ds_stacked_ensemble_automl_algo_save_results`
* Takes a long time to run. We should add flag to disable stacked ensembling in automl.
* Use `self.data_split` to compute the T/V split we score with in `_compute_ensemble_scores`, so that the sole split we score on is identical to the (first) one used for all other pipelines.
    * If needed, to work around #1126 bug when we're using `TrainingValidationSplit`, let's use `reset_index`. Hopefully not necessary now that we're not manually creating `TrainingValidationSplit`
