### ISSUE TITLE
Visualize Decision Trees

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#1239]
As an evalml user, I'd like to be able to visualize a decision tree classifier or regressor to understand and debug my features and estimator.

While this issue tracks visualizing a single tree, we can explore visualizing an ensemble of trees as well - like Catboost, RandomForest - in the future.

**Comment by freddyaboulton** [comment]
I was poking around sklearn and saw that they have utils for exporting trees to text or a graphviz data format. Since we already have graphviz as one of our requirements we could easily visualize the graph like we visualize the pipeline component graph.

However it would be nice if we could extract the tree structure to a friendlier data format than either text or graphviz because it would allow users to visualize the tree with their own plotting library, like plotly. This follows the pattern we have for our other model understanding methods where we first get the data to visualize and then visualize it but it's a higher lift than using the sklearn utils. 

What's do you guys think is in scope for this release @dsherry @tyler3991 ?

**Comment by dsherry** [comment]
@freddyaboulton good point!

I think there's value in building an intermediate data format now, because evalml users can use that to do a custom visualization in their UI/application. So that would be my preference.

Whoever picks this up: you can choose either path, a) build graphviz method or b) build a graphviz method and build an intermediate data function. But if you choose A please file something separately for the intermediate data function!
