### ISSUE TITLE
Error installing evalml (shap) when using python 3.6

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#1242]
While testing the latest release, I tried creating a new virtualenv and installing evalml but ran into the following error:

```
Collecting shap>=0.35.0 (from evalml)
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/d2/17/37ee6c79cafbd9bb7423b54e55ea90beec66aa7638664d607bcc28de0bae/shap-0.36.0.tar.gz
No files/directories in /private/var/folders/pq/zlxt5w357570xxt07x_splf40000gn/T/pip-build-7o0aqjos/shap/pip-egg-info (from PKG-INFO)
```
Repro steps:

```
python3 -m venv test_env
source test_env/bin/activate
pip install evalml
```

I was running `Python 3.6.0`.

Related issue: https://github.com/slundberg/shap/issues/830

The solutions in that issue [here](https://github.com/slundberg/shap/issues/830#issuecomment-537382789) or [here](https://github.com/slundberg/shap/issues/830#issuecomment-692601174) solved the error but could still be worth looking into.

**Comment by bchen1116** [comment]
Found that `pip >= 18.0` and 'setuptools >= 40.0.0` works to avoid this error

**Comment by dsherry** [comment]
@bchen1116 @angela97lin yep. I tried this with python 3.6.10 and didn't get this error, but I was able to get the error with python 3.6.0.

Thing is, adding `pip>=18.0` and `setuptools>=40.0.0` to `core-requirements.txt` doesn't upgrade pip and setuptools *before* installation, so it doesn't fix the problem.

So I think we should list this in our install guide, and not include this in our requirements because that doesn't help. In short, I agree with what's in your PR @bchen1116 ! Will comment there :)
