### ISSUE TITLE
Add predicted-vs-actual plot for timeseries regression

### ISSUE THREAD

**Issue by bchen1116** [alteryx/evalml#1258]
PR [1252](https://github.com/alteryx/evalml/pull/1252) addressed adding prediction vs actual plots for regression in issue #772. Submitting a new issue to address adding a plot for timeseries data.

**Comment by freddyaboulton** [comment]
@dsherry @tyler3991 @bchen1116 I think this is in scope for the time series work we have slated for December. I'm thinking we can overlay the predictions and targets with dates on the x-axis like so:

![image](https://user-images.githubusercontent.com/41651716/100757469-68cbff80-33bc-11eb-8b0e-143a911b9b5f.png)

The api can be something like:

```python
graph_prediction_vs_actual_time_series(pipeline, X, y, dates)
```

What do you guys think?

**Comment by dsherry** [comment]
@freddyaboulton that looks great!

One note on the API: if the graph method expects a `DataFrame` as input, that will include a `time_index` attribute which takes care of the date, instead of asking for it as a 4th argument. We're working on updating all the evalml utils/graph methods to use woodwork (#1229). So, you could coordinate with @angela97lin and upgrade this one to use woodwork sooner than the others, or you could just use the API you've proposed and we'll upgrade it when we do the others; either way works.

**Comment by angela97lin** [comment]
@dsherry @freddyaboulton I'm good with updating in #1229 😁
