### ISSUE TITLE
Add CI test for Python 3.9

### ISSUE THREAD

**Issue by gsheni** [alteryx/evalml#1263]
- With the release of Python 3.9, we should test our CI in an environment with Python 3.9
- https://www.python.org/downloads/release/python-390/

**Comment by angela97lin** [comment]
Great idea! This might be blocking until CircleCI has an image for 3.9.0 though (https://circleci.com/docs/2.0/docker-image-tags.json)

**Comment by dsherry** [comment]
@gsheni closed #1283 because [numpy doesn't support 3.9 yet](https://numpy.org/news/). Let's revisit this when numpy adds that support.

**Comment by angela97lin** [comment]
I tried a variety of different things to get python 3.9 working. It looks like since the last time @gsheni tried, numpy has added support for Python 3.9 via numpy 1.19.3 and above. However, it looks like a package of a package we need (featuretools-->distributed-->pyarrow) still does not have wheels for 3.9 yet. The latest version (2.0.0) of pyarrow also specifies numpy==1.16.0 for versions of python 3.7.0 and above. This breaks, since numpy 1.16.0 doesn't have a python 3.9 wheel.

The bright side is, it seems that the team is aware of this and is working on adding the python 3.9 wheel. The attached issues seem to suggest that we could see this addition soon (01-2021 release)!

https://github.com/apache/arrow/pull/8915
https://github.com/apache/arrow/pull/8386


Some useful output from failed tests:
https://circleci.com/api/v1.1/project/github/alteryx/evalml/108170/output/103/0?file=true&allocation-id=600b511763ecf124a9f28fa9-0-build%2F26747107
https://app.circleci.com/pipelines/github/alteryx/evalml/9183/workflows/7e22bb52-91ae-4db3-bb1f-ef8760b3cae2/jobs/108188

**Comment by angela97lin** [comment]
@dsherry I'll put this back in the backlog for now, and we can revisit in a few weeks to see if this issue has been resolved, does that sound good?

**Comment by angela97lin** [comment]
Dug into Woodwork code, and it looks like pyarrow is used in order to support serialization (parquet): https://github.com/alteryx/woodwork/blob/a867b2188448de369c8f659e898a8f1ec446a5b3/woodwork/datatable.py

Going to try manually installing all other dependencies and then installing woodwork without installing its dependencies to see if anything else breaks 👀

**Comment by angela97lin** [comment]
This is currently blocking on https://github.com/alteryx/woodwork/issues/505!

**Comment by angela97lin** [comment]
Not sure how this isn't an issue via CircleCI but trying to run locally, I run into: https://github.com/numba/llvmlite/issues/621
... which again goes back to numba not yet supporting Python 3.9.

**Comment by angela97lin** [comment]
This issue is currently blocked on numba/llvmlite not supporting Python 3.9. Looks like release with support for 3.9 could be out soon, so exciting (https://github.com/numba/numba/issues/6684), but putting into backlog until then.
