### ISSUE TITLE
Make stdout and debug logging easily configurable

### ISSUE THREAD

**Issue by SydneyAyx** [alteryx/evalml#1273]
Running an evalml script over a command prompt results in a lot of print outs during the search. It would be nice to be able to "silence" these print outs.

**Comment by dsherry** [comment]
@SydneyAyx thanks for filing! Yep, we should make it easy to configure evalml's behavior here, so that it works better as a submodule. If a third-party dependency I installed started printing stuff to stdout and there was no way to turn that off, I'd be pretty annoyed.

Goals:
* Make stdout output configurable
* Make it easier to configure output to debug log

We should revisit our current logging setup. We have [a mechanism](https://evalml.alteryx.com/en/stable/user_guide/utilities.html#Configuring-Logging) for suppressing or changing the location of the debug log, but we should streamline it for the case when evalml is a pip dependency in a larger project. What do other python libraries do on this front? I think they simply use the std logger, like we do, but they don't force default behavior on users. Perhaps we should redefine our logging so that the debug log is disabled by default, but can be enabled using a util method.

**Comment by dsherry** [comment]
Ah, this is actually a dup of #1174  -- closing in favor of that because its older.
