### ISSUE TITLE
Add GAM regressor and classifier

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#1307]
[This](https://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/gam.html) could be a good place to start

**Comment by dsherry** [comment]
@ParthivNaresh what's the status of this?

**Comment by ParthivNaresh** [comment]
@dsherry I'm having a number of issues with this because of the constant errors that pop up. We can't run GAM against the basic datasets because of its parameters have to be fine tuned for each set otherwise we get errors related to the `num_knots`. And because of the Java backend I can't dig deeper into the cause and can't check for it.
I have a PR for this #1674 but until I can complete comprehensive enough tests for it, we can add this to the backlog.

**Comment by ParthivNaresh** [comment]
Removing myself from this until we can have a broader discussion around GAM and how it should be implemented considering the above mentioned blockers.

**Comment by rpeck** [comment]
I'd be happy to pitch in on this when it rises in the priority queue. :-)

Other H2O-3 stuff it'd be good to have are their GBM, which has some nice features for categorical and NA handling as well as monotonicity constraints, and isolation forests for anomaly detection. There is also a new feature for extracting feature interactions from their GBM and XGBoost extension, which would be great for our AutoML.

When we circle back to this we ought to decide overall what if anything we want to do with H2O-3 integration and make an epic for it.

**Comment by ParthivNaresh** [comment]
@dsherry Let's chat about this
