### ISSUE TITLE
LightGBM "invalid value encountered" warning during fit

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#1343]
Repro: load breast cancer dataset and run automl. As is currently visible [on the start page in the docs](https://evalml.alteryx.com/en/latest/start.html) 😅
> invalid value encountered in double_scalars

Tagging @bchen1116 as this could be related to recent lightgbm changes

**Comment by bchen1116** [comment]
@dsherry Looked further into this issue. It isn't a LightGBM issue, it's an issue in `HighVarianceCVDataCheck` when we try to add the baseline scores to it. The issue is that the `cv_scores` of baseline are 0, so when it does `cv_scores.std(), cv_scores.mean()`, numpy throws this warning. This should be fixable with a simple check that the values aren't all 0 / `nan`

![Uploading Screen Shot 2020-10-26 at 11.41.13 AM.png…]()
