### ISSUE TITLE
Investigate if binary classification problems still require numerical {0, 1} targets

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#1422]
Now that we've implemented LabelEncoder, do we still need the check in `InvalidTargetDataCheck`? If not, we should delete it and update docs accordingly.

---

Is the last point still true? Now that we have the label encoder in the classification pipeline, I think this use case will work fine. If I'm right, can we file something to either delete this from `InvalidTargetDataCheck`, or change it to a warning instead of an error? Certainly, providing something which looks suspicious could indicate the user has provided incorrect data for some reason, which makes me think showing a warning is a good idea rather than just deleting.

_Originally posted by @dsherry in https://github.com/alteryx/evalml/pull/1412#discussion_r520073251_

**Comment by freddyaboulton** [comment]
We technically don't need that part of the check anymore because @dsherry is right that the label encoder will automatically encode the values into [0, n_classes - 1]. I think we should change from error to warning because I'd be suspicious if someone meant to use a numeric column that doesn't have [0, 1] as the target value. It's possible they're using a numeric column that only happens to have two unique values in the sample but that doesn't correspond to any "classes" at all. 

```python
from evalml.pipelines import BinaryClassificationPipeline
from evalml.demos import load_breast_cancer

class DemoPipeline(BinaryClassificationPipeline):
    component_graph = ["Logistic Regression Classifier"]
    
X, y = load_breast_cancer()

y_ints = y.map({"malignant": 4.89, "benign": 8.78})

pl = DemoPipeline({})

pl.fit(X, y_ints)
```

```python
pl.predict_proba(X)
```

4.89 | 8.78
-- | --
1.000000 | 3.933512e-15
1.000000 | 2.638231e-08
1.000000 | 2.157034e-07
0.151240 | 8.487604e-01
0.999996 | 4.049651e-06

**Comment by angela97lin** [comment]
@freddyaboulton You're absolutely right! I ran this locally and got the same results as you. Just realized that since I updated #1451 to convert the data check to return a warning instead of an error, this issue is resolved.
