### ISSUE TITLE
AutoML Search API with no warnings

### ISSUE THREAD

**Issue by gsheni** [alteryx/evalml#1426]
- As a first time user of EvalML, I want to pass a DataFrame along with typing information to AutoML Search without having to learn another library (Woodwork). 
- A minor adjustment to Search and the addition of a data types dictionary would allow me to do this.
- https://alteryx.quip.com/4DepAA8DuBWu/EvalML-Woodwork-API-Suggestion

```python
data_types = {
    'id': 'index',
    'transaction_time': 'time_index',
    'gender': 'Categorical', 
    'comments': 'NaturalLanguage'
}

# pass pd.DataFrame + dict to AutoML Search
automl.search(X_train, y_train, data_types=data_types)
```

**Comment by angela97lin** [comment]
After discussion with @dsherry we decided that adding a utility method that allows users to do this transformation without having to directly interface with Woodwork seems like a good compromise, rather than changing AutoMLSearch's API (and the rest of evalml). That issue is being tracked by #1545, so closing this.
