### ISSUE TITLE
Prediction explanations: output pandas dataframe

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#1434]
For easy programmatic access, let's update our prediction explanation feature to output a pandas dataframe.

We can choose to keep the current human-readable print format, as long as we have an intermediate representation in a dataframe.

This comes from feedback from the Oct 2020 blitz.

**Comment by freddyaboulton** [comment]
@dsherry Since our prediction explanation output is nested by design so we need to make a design choice about how to make the translation to a dataframe.

I think there are levels of un-nesting:

1. None
![image](https://user-images.githubusercontent.com/41651716/102135699-56bf7780-3e26-11eb-9be2-b95a86da3a28.png)

2. Partial
![image](https://user-images.githubusercontent.com/41651716/102135764-6f2f9200-3e26-11eb-9267-635a9d5e7382.png)


3. Complete
![image](https://user-images.githubusercontent.com/41651716/102135838-8d958d80-3e26-11eb-9326-437f3164e009.png)

I prefer 3 but I'm not sure how much more value this adds over our existing "dict" format. If the goal is  "easy programmatic access", maybe we don't add a dataframe output format and instead make `output_fotmat=dict` the default?

**Comment by freddyaboulton** [comment]
@dsherry @chukarsten Before we do this in the next sprint, what are your thoughts on the above? I'm not sure a dataframe is more helpful than our dict format.

**Comment by chukarsten** [comment]
I guess what I would ask is: how is this going to be used, how much is it going to be used and by who?  I could see an argument for users that want to explore the predictions in a way that's more intuitive to them (I'm making the assumption that data scientists are more fluent in manipulating data frames vs. pure python), that a pandas output would be nice.  If we decide to sally forth with it, I agree that the third option is the most clear.  It also seems like it would be nice for the predicted probabilities to also be a column.

But seeing as you've basically already unraveled the dict, it seems like it's not a tough lift to pick the third and just go with it.
