### ISSUE TITLE
Featuretools component

### ISSUE THREAD

**Issue by tyler3991** [alteryx/evalml#1446]

**Comment by bchen1116** [comment]
After discussion with @dsherry, we've decided to close this epic for now. Our primary reasons for pausing the Featuretools integration are as follows:
- Featuretools is largely a data preprocessing/generating step, which is fairly distinct from EvalML. There currently is no way for us to alleviate the steps that a user would go through in order to make the Featuretools to EvalML transition smoother and faster for users
    - Since a user has to generate the entityset on their own (because there are so many possible variables to alter), EvalML can really only run the DFS step, which isn't very useful to add as an EvalML component versus having users continue through Featuretools
- With an entityset input, we cannot easily generate train/test data to run AutoML on. Additionally, Featuretools seems to be created with the purpose to generate the feature matrix before separating the data, and this choice doesn't easily integrate with EvalML

We leave our full notes in the following [doc](https://alteryx.quip.com/qRaoAZQEuIg8/Featuretools-multi-table-notes).
