### ISSUE TITLE
Improve error msg when non-string objective provided without required args

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#1603]
From December Blitz: https://alteryx.quip.com/hifwAO0YHqul/Blitz-December-2020-Notes

![image (6)](https://user-images.githubusercontent.com/5422235/103105033-08b22d00-45f9-11eb-8ffc-6de18aaf6c9e.png)

**Comment by dsherry** [comment]
Possibilities here:
1. We expect that for any objective which has constructor args, you can't refer to that objective by string name, have to pass instance
2. Define API to accept objective parameters in the call to `score`

I think 1 is simpler and therefore I like it more.

**Comment by freddyaboulton** [comment]
@dsherry @angela97lin I think the code is already doing option 1. The `TypeError` is raised by evalml and it's saying that the cost benefit matrix is missing four required arguments in init. 

I agree the error message is a bit confusing. Ideally, it should be something actionable like:

`Cannot pass cost benefit matrix as a string in pipeline.score. Instantiate it first and then pass it as one of the objectives.` 

The problem is that the exception is currently raised within `get_objective` which doesn't know it's being called from `pipeline.score`. We can catch this exception from `pipeline.score` and provide the clearer message. Does that sound good?
