### ISSUE TITLE
Integrate graphviz version 0.16

### ISSUE THREAD

**Issue by jeremyliweishih** [alteryx/evalml#1617]
When graphviz version 0.16 was released, it broke our windows unit tests (seen [here](https://github.com/alteryx/evalml/runs/1606320959)) by introducing a new graphing engine called `dot`. This issue tracks the following:

- add documentation on installing graphviz version 0.16 using conda
- uncapping the graphviz version in `requirements.txt`
- unpinning the graphviz version in `config.yml` for our windows unit tests.

**Comment by rwedge** [comment]
Update on this issue:
* Issue is with the conda version of graphviz 0.16 on Windows specifically
* Conda version of graphviz on Windows needs the conda version of the python graphviz library to work correctly
* Conda python-graphviz package patches the regular python graphviz code to work with the conda version on Windows.  A change in the regular code in 0.16 added a new place that would need to be patched.  It hasn't been patched yet, so the conda version of 0.16 doesn't work on windows.
* Relevant issue here: https://github.com/conda-forge/python-graphviz-feedstock/issues/42

Since this is limited to graphviz 0.16 on conda specifically, capping graphviz outside of the windows unit tests may not be necessary
