### ISSUE TITLE
Delete FeatureLabs evalml-core-feedstock fork, add conda update dev guide

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#1620]
Conda-forge asks that any PR to update the [evalml feedstock](https://github.com/conda-forge/evalml-core-feedstock) comes from [a personal fork](https://github.com/dsherry/evalml-core-feedstock), meaning one that you create individually using your github account, rather than using a fork owned by our organization. [The reason for this](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork), I believe, is that forks in GitHub which are owned by orgs cannot give the "Allow edits from maintainers" permission, but forks owned by individuals can.

I'm filing this to ask @freddyaboulton : is there any reason we should keep the FeatureLabs fork of the evalml feedstock, or can we delete it to avoid confusion? I'd like to delete it :)

Also, this tracks writing / updating a process doc somewhere in the evalml repo to describe what is required to make changes to the conda feedstock. This could go into [the `contributing` guide](https://github.com/alteryx/evalml/blob/main/contributing.md), or we could find a different place.

**Comment by freddyaboulton** [comment]
@dsherry Sure we can delete the FeatureLabs fork! I created that fork because I saw there was one for featuretools under the FeatureLabs org. I didn't mind rerendering locally so I didn't see "Allow edits from maintainers" as a must-have. 

I'll add a section to our contributing guidelines about the update process:
1. creating a personal fork
2. Making changes to meta.yaml
3. rerendering
