### ISSUE TITLE
Make it easy to freeze individual parameters during automl search

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#1625]
**Example**
Suppose I want to run automl, but because of my knowledge about the dataset and the domain in question, I know I want to use the "most_frequent" imputation strategy for filling missing values, rather than letting automl gradually try to find the best imputation strategy. In that case, it would be convenient if automl allowed me to input that parameter setting before the search begins.

**Problem**
This is supported today, but via the following ugly path:
* Run `make_pipelines` by hand to get the pipelines which automl would generate for your problem
* Subclass those pipelines, and for any parameter you'd like to fix to one value, set it to that single value in the `custom_hyperparameter_ranges` for each pipeline
* Run automl with a list of the pipeline classes you created

We can improve on that.

This has come up a few times in the past few months; thanks @bchen1116 for finally pushing me to file it 😆

**Comment by bchen1116** [comment]
@dsherry Wrote a quick [design doc](https://alteryx.quip.com/9wcHAca7Ioo1/AutoMLSearch-API-Parameters-for-Pipelines) for this issue. I think the value-add of this, in comparison to the already-existing `custom_hyperparameters` arg in `make_pipelines`, is that it would allow the user to both easily set the params as well as set params to values that aren't equal to the component defaults. More info in the doc.

**Comment by bchen1116** [comment]
Results from discussion with @dsherry 

1. Alter the `tuner` class to not include singular variables in the search space. For instance, if I pass in 
   ```python
   parameters = {"Imputer": {"categorical_impute_strategy": "constant"}}
   ```
   then the `categorical_impute_strategy` won't be included in the tuner search space. Make sure that single variables work 
   with AutoMLSearch
2. Add support for lists/`skopt.space` objects in the parameters dictionary for AutoMLSearch. Ensure that this works even if  the default values for parameters aren't in the ranges provided, ie 
   ```python
   parameters = {"Imputer": {"numeric_impute_strategy": ["constant", "mode"]}}
   ```
   since the default param is `mean`. 

These would be 2 separate PRs
