### ISSUE TITLE
Drop support for python 3.6

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#1712]
Per https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table, the drop support for 3.6 should have happened on Jun 23, 2020 drop support for Python 3.6 (initially released on Dec 23, 2016).

However, looking at the docs for numpy: https://numpy.org/doc/stable/release/1.19.0-notes.html
```
The Python versions supported for this release are 3.6-3.8. Downstream developers should use Cython >= 0.29.16 for Python 3.8 support and OpenBLAS >= 3.7 to avoid problems on the Skylake architecture.
```

It's important to also note that python 3.9 is not listed. We need to check that numpy supports python 3.9

EDIT: Looks like numpy 1.19.3 supports 3.9, so we would have to update our min version to this: https://github.com/numpy/numpy/releases/tag/v1.19.3

**Comment by angela97lin** [comment]
Update on this: we should sync with other teams to make sure that dropping 3.6 will not cause any issues.

**Comment by dsherry** [comment]
Reminder that one of our motivators for doing this soon rather than waiting for [python 3.6 end-of-life in Dec 2021](https://www.python.org/downloads/) is that the latest version of pandas (1.2.0) [doesn't support python 3.6](https://github.com/alteryx/evalml/issues/1618#issuecomment-763615732). Its ok if our python 3.6 CI runs with an older version of pandas. But if the versions continue to drift it could lead to undesirable differences in behavior, which we shouldn't invest in fixing if python 3.6 is out in ~12mo.
