### ISSUE TITLE
Stable version of docs won't update

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#1777]
Symptom: When we did the 0.18.0 release, and now the 0.18.1 release, RTD didn't update `stable` to point to the new version.

`latest` and `main` updated successfully, and we were able to create `v0.18.0` and `v0.18.1` versions.

**Comment by dsherry** [comment]
@bchen1116 did support have anything to add?

**Comment by dsherry** [comment]
@bchen1116 said:
> No current update from the support team. I just changed our automation build in RTD to build for any tags rather than the custom match we had before, which might be the issue. Unsure though, since I don’t think it acts retroactively, so we might have to wait for the next release before seeing if the change works

**Comment by dsherry** [comment]
Plan: since @bchen1116 changed automation rules just now, we'll wait for next release. If we still have issues, we'll ping support again.

**Comment by freddyaboulton** [comment]
I think we can close this? Looks like stable finally includes the 0.18.2 release

https://evalml.alteryx.com/en/stable/release_notes.html

**Comment by angela97lin** [comment]
Should we just wait for release next week to double-triple-check? :)

**Comment by bchen1116** [comment]
@angela97lin @freddyaboulton I believe @dsherry set up a separate stable branch to build from and replace the automatic stable builds we should have (note that stable doesn't have the tag that `v0.18.2` has):
![image](https://user-images.githubusercontent.com/22552445/108738594-c8403400-7501-11eb-87b1-80911f34c7c1.png)

I think this issue is still a problem, but not sure what the fixes could be. Looks like as long as we use [semantic versioning for the tags](https://docs.readthedocs.io/en/stable/versions.html#how-we-envision-versions-working), it should update stable, but I'm not sure if this was a recent change? I don't think our tags of `vX.Y.Z` qualify as semantic versions, since their examples seem to push for tags `X.Y.Z`. Potentially we have to change our tagging style, but I could be reading into this incorrectly.

Issue should stay open since it's unsolved for now.

**Comment by chukarsten** [comment]
With v.0.19.0 this is still an issue

**Comment by dsherry** [comment]
We're still having trouble with this with v0.24.1. I sent another email to support and we'll see what happens.

**Comment by dsherry** [comment]
I communicated with RTD support and they said they made a change on the backend a couple weeks ago. The 0.25.0 release updated `stable`! So we're good to go.
