### ISSUE TITLE
Update `describe_pipeline` to return more information about pipeline, including id for ensemble

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#1872]
Fallout of https://alteryx.quip.com/VyJ6Ac1sAc7c/AutoML-Ensembling-Indicate-which-pipelines-were-selected-for-ensembling.

We should update `describe_pipeline` s.t. when we want to describe an ensemble pipeline, we return information about the ids of the pipelines that were used to build the ensemble pipeline.

**Comment by dsherry** [comment]
@angela97lin let's remove "including id for ensemble" from the title here. There won't be a way to get that info until #1873 is done, but that's marked as blocked on this issue. I suggest you:
* Update this issue title to say "including pipeline ID" instead of "including id for ensemble"
* Update #1873 to include updating `describe_pipeline` to include ensemble IDs in `describe_pipeline`
