### ISSUE TITLE
Ability to save pipelines using pickle

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#1956]
*Background*
The pipeline `save` and `load` methods currently [use `cloudpickle`](https://github.com/cloudpipe/cloudpickle) instead of [python `pickle`](https://docs.python.org/3/library/pickle.html#:~:text=%E2%80%9CPickling%E2%80%9D%20is%20the%20process%20whereby,back%20into%20an%20object%20hierarchy.).

We closed #1400 a couple months ago. But this led to a bug (#1912) where our code was setting class attributes which apply across all instances of our template classes.

*Plan*
The short-term resolution for #1912 is to revert the change for #1400, so that `get_pipelines` returns a pipeline instance which is *not* `pickle`-able using python `pickle` but also does not have the buggy side-effect behavior when it comes to the class attributes like `name` and `component_graph`

Once that's done, this issue tracks figuring out how we can modify our approach to support python `pickle` of our pipelines, and filing issues to execute that plan.

**Comment by angela97lin** [comment]
The issue at hand is that `make_pipeline` returns a dynamically-generated class and `pickle` is not able to pickle dynamic classes.

Options:
- Be explicit about not supporting `pickle` and requiring users to use `cloudpickle` if they want to save their pipelines.
- Right now, we need this dynamically-generated class because we expect a pipeline class to have specific attributes (custom name. component graph, custom hyperparameters). We could move from storing those as class attributes to instance attributes. These were added in https://github.com/alteryx/evalml/issues/345 to facilitate the ease of creating new pipelines, but it could be worth revisiting again.

**Comment by dsherry** [comment]
@chukarsten suggested looking at defining `reduce` on our pipelines. I think that could be the way to go.

https://stackoverflow.com/questions/11658511/pickling-dynamically-generated-classes

However that does leave us with another challenge. Currently we define the pipeline classes used in automl at runtime. I think the original issue was that those definitions weren't being found/saved during the pickling. That issue still needs a solution.

**Comment by dsherry** [comment]
We did some digging this morning and [listed options](https://alteryx.quip.com/HHUUAcb4QVwC/Pickling).

**Comment by angela97lin** [comment]
Next steps: open a spike PR, see what difficulties we encounter with updating our pipeline API.
