### ISSUE TITLE
Mode Baseline Binary Classification Pipeline

### ISSUE THREAD

**Issue by moezali1** [alteryx/evalml#2067]
Hi,

I was following through this tutorial: https://evalml.alteryx.com/en/stable/start.html

I noticed the following rankings of `automl.search`

![image](https://user-images.githubusercontent.com/54699234/113298842-3d094980-92ca-11eb-817f-7f8880e7b660.png)

Notice that the score of `Mode Baseline Binary Classification Pipeline` is 0.0000. The dataset used in this tutorial has a target distribution of ~ 85/15. So even if the base classifier is predicting the majority class as a prediction for all observations, the score will still be >0. 

Accordingly, `percent_better_than_baseline` values will also change for all models, given that this turns out to be a bug.

**Comment by dsherry** [comment]
Thanks @moezali1 ! Yes that is clearly not the correct F1 score for this dataset. Marked as a bug.

**Comment by kmax12** [comment]
the `percent_better_than_baseline` also seems off in that screenshot since it is just the score*100

**Comment by bchen1116** [comment]
@dsherry @moezali1, I believe this score is correct! Since the AutoMLSearch algorithm in our [start.ipynb](https://evalml.alteryx.com/en/v0.19.0/start.html#Start) notebook uses F1 score as the default objective, a model that predicts only a single value (in this case, False) on all samples would result in a recall score=0, which results in the F1 score also being 0. I'm creating a quick fix in our docs to make it clearer, which I will post here when it's ready!
