### ISSUE TITLE
Baseline pipeline reported as having high classification accuracy

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#2080]
**Problem**
On this imbalanced binary classification dataset, when "accuracy binary" is selected as the objective, the baseline model is reported to have performed the _best_ of all pipelines. This is incorrect by definition!

**Repro**
(Make sure you use woodwork 0.0.11 since we don't yet support 0.1.X)
Download [kaggle stroke prediction dataset](https://www.kaggle.com/fedesoriano/stroke-prediction-dataset)
Set "stroke" as the target
```
import evalml
import pandas as pd
import woodwork as ww
df = pd.read_csv('/Users/dylan.sherry/Downloads/Stroke Predictors.csv')
dt = ww.DataTable(df)
y = dt.pop('stroke')
automl_acc = evalml.AutoMLSearch(X_train=dt, y_train=y, problem_type='binary', objective='accuracy binary')
automl_acc.search()
```
Note that the baseline model has the highest accuracy reported, tied with ElasticNet, at 0.951291. This is not correct!

If you run the same but with log loss or F1, the baseline model scores the worst as expected.

**Comment by jeremyliweishih** [comment]
This particular dataset contains 4861 negative labels and 249 positive labels for a total of 5110 examples. Accuracy is calculated by `Accuracy = (TP + TN)/(TP + TN + FP + FN)`. If we predict the mode (which is the negative label) for every prediction we will get: TP = 0, TN = 4861, FP = 0, FN = 249 which will give us an accuracy of 4861 / 5110 = 0.95. Running AutoML Search we see that the baseline pipeline has an accuracy of 0.951291 and this result is matched by ElasticNet as well. The above calculations show that this result by the baseline pipeline is not a bug but rather a consequence of using accuracy on a heavily imbalanced problem. This is because accuracy only takes class labels into account and does not penalize wrong predictions as hard as a metric like log loss. Thus, the mode prediction that the mode baseline uses performs well based off of accuracy. If we use log loss as our AutoML metric we can see that the baseline does score the worst. 

The attached notebook explores the above in code form.
[baseline_top_pipeline_example.ipynb.zip](https://github.com/alteryx/evalml/files/6380291/baseline_top_pipeline_example.ipynb.zip)
