### ISSUE TITLE
Add Gini coefficient as an objective

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#2102]
Mentioned during standup, the Gini coefficient would be a good metric to add to EvalML.

**Comment by dsherry** [comment]
@eccabay RE our discussion yesterday, let's move forward with adding a GINI objective to EvalML for binary classification.

I think [this guide](https://towardsdatascience.com/using-the-gini-coefficient-to-evaluate-the-performance-of-credit-score-models-59fe13ef420) provides a lot of good info about GINI coefficient.
> [The] Gini coefficient is one of the most popular metrics used by the financial industry for evaluating the performance of credit score models.

[This paper](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2739245), referenced in the above article, states that we can compute GINI as `GINI = 2 * AUC - 1`.

Since we know AUC has range `[0, 1]` by definition, GINI will therefore have range `[-1, 1]`.

A bit more context from that paper helps explain the intuition behind the mechanics of GINI and the relationship of GINI and AUC
> There are more than a dozen equivalent ways to present Gini (Yitzhaki, 1998). The original one (Gini, 1914) is G(X) = E|X1 −X2| where X1 and X2 are independent and identically distributed copies of X

So essentially, GINI is a way to measure how far a distribution's [probability density function](https://en.wikipedia.org/wiki/Probability_density_function) (PDF) deviates from a uniform distribution. Or, how far the [cumulative distribution function](https://en.wikipedia.org/wiki/Cumulative_distribution_function) (CDF) deviates from the line `f(x) = x`, i.e. 1:1 correspondence.

Take the fully random case as an example. A model which makes uniform random classifications will have a linear ROC curve of `true_positives(false_positives) = false_positives`, and therefore an AUC of approximately 0.5. This makes sense: if the binary classification models' predicted probabilities are drawn from a uniform distribution, as we sweep the bin class threshold from 0 to 1, the percentage of both false positives and true positives will grow approximately linearly from 0 to 1. Applying the GINI transformation above gives a value of 0. This also makes sense: that linear ROC curve represents a [continuous uniform distribution](https://en.wikipedia.org/wiki/Continuous_uniform_distribution).

**Comment by eccabay** [comment]
@dsherry I was in the process of writing up a similar summary, you beat me to it! I took a look at h2o and DataRobot, and it seems like they each only provide the Gini coefficient as a binary classification metric and not for multiclass. I think at least for the time being it makes sense for us to do similar.
