### ISSUE TITLE
Partial Dependence Contour Plots Showing NaNs in our model understanding demo

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#2115]
In our model understanding demo, our two-way partial dependence plot shows NaN in the right-most region of the plot:

![image](https://user-images.githubusercontent.com/41651716/113935611-bc17e980-97c4-11eb-9e25-4780106a9a74.png)

Is this expected? I think we may be extending the x axis range farther than it should?

**Comment by chukarsten** [comment]
@freddyaboulton No, this is not expected, some sort of cleaning needs to be done to take care of this.

**Comment by dsherry** [comment]
@freddyaboulton in #2117 you said:
> Fixes #2056, #2115

FYI for future reference, unfortunately [the GitHub "fixes" keyword](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) doesn't support that syntax! You have to say
> Fixes #2056, fixes #2115

Closing this issue as it was fixed by #2117
