### ISSUE TITLE
Partial dependence null warnings not being issued for two-way partial dependence

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#2119]
Repro

```python
from evalml.pipelines import BinaryClassificationPipeline
from evalml.model_understanding import partial_dependence
import pandas as pd
import numpy as np

class Pipeline(BinaryClassificationPipeline):
    component_graph = ["Imputer", "Random Forest Classifier"]
    
pl = Pipeline({})

X = pd.DataFrame({"a": [1, 2, 3],
                  "b": [4, 5, 6]})
y = pd.Series([0, 1, 0])
pl.fit(X, y)

pred_df = pd.DataFrame({"a":  np.random.random(99).tolist() + [None], "b": [1] + [None]*99})
partial_dependence(pl, pred_df, features=("a", "b"), grid_resolution=10)
```

I would expect the `There are null values in the features, which will cause NaN values in the partial dependence output.` warning to show up along with the `Feature 'b' is mostly one value, 1.0, and cannot be used to compute partial dependence.` value error.

**Comment by dsherry** [comment]
@freddyaboulton in #2120  you said:
> Fixes #2073, #2119

FYI for future reference, unfortunately [the GitHub "fixes" keyword](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) doesn't support that syntax! You have to say
> Fixes #2073, fixes #2119

Closing this issue as it was fixed by #2120
