### ISSUE TITLE
AutoMLSearch: clean up API for freezing parameters and constraining hyperparam ranges

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#2130]
Repro

```python
from evalml.demos import load_breast_cancer
from evalml.pipelines import BinaryClassificationPipeline
from skopt.space import Categorical
from evalml.automl import AutoMLSearch
import pytest

X, y = load_breast_cancer()    

automl = AutoMLSearch(X, y, problem_type="binary",
                      max_batches=2,
                      pipeline_parameters={"Imputer": {"numeric_impute_strategy": "most_frequent"}})
automl.search()
all_imputer_params = automl.full_rankings.iloc[:-1].parameters.map(lambda d: d['Imputer']['numeric_impute_strategy'])
assert set(all_imputer_params) == {'most_frequent', 'mean'}
```

However using `skopt.space.Categorical` works.

```python
automl = AutoMLSearch(X, y, problem_type="binary",
                      max_batches=2,
                      pipeline_parameters={"Imputer": {"numeric_impute_strategy": Categorical(["most_frequent"])}})
automl.search()
all_imputer_params = automl.full_rankings.iloc[:-1].parameters.map(lambda d: d['Imputer']['numeric_impute_strategy'])
assert set(all_imputer_params) == {'most_frequent'}
```

I think the problem is that skopt does not recognize `most_frequent` as a valid hyperparameter space so it will silently not include it in the `proposed_parameters` dict. Note that we can't specify `["most_frequent"]` because of #2028. 

I think the right thing to do is to not let users pass in "scalar-valued" hyperparameters.

**Comment by dsherry** [comment]
Thanks for this. I would categorize this as saying the `pipeline_parameters` input is not behaving the way we want it to. Not sure I follow the scalar-valued suggestion yet but I think we can update our tuner code to avoid this issue.

**Comment by jeremyliweishih** [comment]
[Here](https://github.com/alteryx/evalml/pull/2138#issuecomment-822669609) I had a very quick spike on separating custom hyperparameter and pipeline parameter functionality. Ideally, I still think we should try to separate out custom hyperparameters and parameters passed into pipelines. Don't have a concrete plan on how to achieve that but will revist after #2091 and #2130.

**Comment by dsherry** [comment]
This issue lists at least a couple problems with our current approach to handling freezing parameter values and accepting user-specified hyperparameter ranges. Let's use it to track simplifying and cleaning up the API for doing this.

**Comment by angela97lin** [comment]
Currently, we use `pipeline_parameters` in AutoMLSearch to both limit custom hyperparameter ranges and set parameters for pipelines (since a hyperparameter range with one value is equivalent to setting it to that value). This causes issues for cases such as `DropColumn` component, where we have a `columns` parameter which we want to set without setting the hyperparameter range.

Right now, we have `IterativeAlgorithm` hardcoded to handle this case in `_transform_parameters`. However, this is not a sustainable long term solution. #2091 took a stab at separating the two by introducing `frozen_parameters` which are always used and update the parameters before new pipelines are made, but I think it'd be best to take another look and clean up the distinction and logic between the two.

If we choose to separate the two further, it's worth noting that we have to handle the case where the user sets both and the two conflict. Ex: Hyperparameter range has {"a", "b"}, user sets parameter as "c".

**Comment by dsherry** [comment]
Question: how do users specify a) freezing parameters and b) custom hyperparameter ranges, constraining automl parameters.

Proposal from discussion with @angela97lin today: delete `custom_hyperparameters` from pipelines. Only use `pipeline_params`, just need to figure out how that can support both a and b above.
