### ISSUE TITLE
AutoMLSearch does not apply pipeline_parameters to custom pipelines 

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#2132]
Repro

```python
from evalml.demos import load_breast_cancer
from evalml.pipelines import BinaryClassificationPipeline
from skopt.space import Categorical
from evalml.automl import AutoMLSearch
import pytest


class PipeLine(BinaryClassificationPipeline):
    component_graph = ["One Hot Encoder", "Random Forest Classifier"]
    
X, y = load_breast_cancer()
automl = AutoMLSearch(X, y, problem_type="binary", allowed_pipelines=[PipeLine],
                      pipeline_parameters={"Random Forest Classifier": {"n_estimators": Categorical([50])}},
                      max_batches=2)
automl.search()

rf_params = automl.full_rankings.iloc[:-1].parameters.map(lambda d: d["Random Forest Classifier"]['n_estimators'])

assert set(rf_params) != {50}
```

I think the issue is that `pipeline_parameters` [is only used](https://github.com/alteryx/evalml/blob/main/evalml/automl/automl_search.py#L291) in `allowed_pipelines` is None.

**Comment by dsherry** [comment]
@freddyaboulton in #2135 you said:
> Fixes #2049, #2132, #2125

FYI for future reference, unfortunately [the GitHub "fixes" keyword](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) doesn't support that syntax! You have to say
> Fixes #2049, fixes #2132, fixes #2125

Closing this issue as it was fixed by #2135
