### ISSUE TITLE
Getting errors during installation and while running in jupyter

### ISSUE THREAD

**Issue by Vinitkumar89** [alteryx/evalml#2153]
Hi,

First i got errors while installing and then when i ran it in jupyter i was not able to import libraries.  like autoregression.

**Comment by chukarsten** [comment]
Hi @Vinitkumar89 , can you post something a bit more specific?  Like some stack traces that you see in jupyter?

**Comment by Vinitkumar89** [comment]
Hi,
i got below error when i try to run it for a regression.
cannot import name 'AutoRegressionSearch' from 'evalml' 

This is what i executed,
import evalml
from evalml import AutoRegressionSearch
from evalml.pipelines import PipelineBase, get_pipelines

it was given on the website
https://evalml.featurelabs.com/en/v0.7.0/automl/regression_example.html

**Comment by dsherry** [comment]
@Vinitkumar89 I see you're referencing the docs from v0.7.0. That version is more than a year old and we've made a lot of updates since then. Our most recent release was v0.23.0.

Which version of EvalML are you using? You can get the version by running `pip freeze | grep evalml` or by running this in python
```python
import evalml
print(evalml.__version__)
```
Please update to our latest version and let us know if you encounter any problems. I'd suggest looking here for guides on getting started:
https://evalml.featurelabs.com/en/stable/start.html
https://evalml.featurelabs.com/en/stable/user_guide/automl.html
