### ISSUE TITLE
Remove `new` and update `clone` to pass an optional parameters parameter

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#2176]
From @dsherry's comment on #2091:

I was initially confused because I got this method mixed up [with `__new__`](https://www.geeksforgeeks.org/__new__-in-python/). I suggest we change the docstring to something like
> Constructs a new instance of the pipeline with the same component graph but with a different set of parameters. Not to be confused with \_\_new__

Adding this in this PR is fine with me.

It does leave me wondering, why do we need both a `new` method and [our current `clone` method](https://github.com/alteryx/evalml/blob/main/evalml/pipelines/pipeline_base.py#L482)? Perhaps we should just update `clone` to optionally accept `parameters` as an argument. Maybe `clone` needs to be renamed to `copy` or `new`. Not required to address in this PR though.

_Originally posted by @dsherry in https://github.com/alteryx/evalml/pull/2091#discussion_r617608120_

**Comment by freddyaboulton** [comment]
The reason `clone` doesn't take any arguments is because we were incorrectly cloning pipelines with the wrong random state. 

I think it's fine if we update `clone` to take `parameters` but maybe let's not let it take `random_state`? We have coverage that automl that we preserve the `random_state` but I worry that it's very easy to sneak in a bug if we let users clone pipelines with different random states.

Maybe the need to do this will be resolved by #2159 ? At that point, the `IterativeAlgorithm` will only have component graphs.

**Comment by dsherry** [comment]
Now that #2091 is merged, I think we should ignore this issue and instead focus on removing the usage of subclassing our base pipeline classes in our codebase (where we redefine clone and new). Closing.
