### ISSUE TITLE
DataChecks: ability to tell which actions came from which data checks

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#2179]
Request from @dancuarini, we should have a code that maps data check actions to natural language strings. For example, we will want distinguish between a no variance col and a potential ID col action. Right now, both return DROP_COL.

**Comment by dsherry** [comment]
I'm not sure I understand the need for this yet. Each data check will return a list of errors, warnings and actions. So the actions aren't all lumped together in one big list, they're split up by the data checks they came from. So I'm not sure we need an additional map for this info, because its already available.

**Comment by dsherry** [comment]
Ok, I think I get it now.

Acceptance criterion: we need a way to associate which data check actions came from which data checks. Currently `DataChecks.validate` will lump everything together.

I'm not sure that having a lookup table is the right way to do this though. Is there some way we can change the output format/structure from `DataChecks.validate` to reflect this info?
