### ISSUE TITLE
Speed up build_conda_pkg

### ISSUE THREAD

**Issue by chukarsten** [alteryx/evalml#2416]
Similar to #2365 and #2404 , `build_conda_pkg`is now a long pole in the CI tent.  Even though the rest of the CI jobs take ~10-12 minutes to run, this one is 30+ minutes and should either be moved to merges to main or effort put into shortening it.

**Comment by freddyaboulton** [comment]
Unfortunately, we don't have a lot of control over the mechanics of the build other than what unit tests we run during the process. 

I think these are the levers we can tweak:

1. Don't run the full set of unit tests in `build_conda_pkg` - feel like this defeats the purpose of the check
2. Run the check on a beefier machine so that we can make use of `-j 8` - I think we're trying to avoid self-hosted runners
3. Like you said, run after merge to main only - I like this. It's what we had before but it does miss the 1% of prs where this check can prevent merging something that will break the conda build.
4. Run only on prs that change requirements files change, e.g. `core-requirements.txt`, `requirements.txt`, `test-requirements.txt`, minimum/latest deps, etc - I like this because I think the only prs that really have a chance of failing `build_conda_pkg` are those that update the requirements in any way.

I think we can do both 3 and 4 and vote we proceed with that. What do you think @chukarsten ? Are there any other quick options I'm missing ?

**Comment by chukarsten** [comment]
I think #4 is a really clever solution and the most robust.  Do you think that can be done?  Like a GH action dependent on whether one of the reqs.txt files is changed?

**Comment by freddyaboulton** [comment]
Yes, I believe so!
