### ISSUE TITLE
Test compatibility with upcoming pandas release 1.3.0 

### ISSUE THREAD

**Issue by gsheni** [alteryx/evalml#2431]
- The [upcoming pandas release](https://pandas.pydata.org/pandas-docs/dev/whatsnew/v1.3.0.html) should be tested with EvalML to make sure upcoming breaking changes are addressed.
- Woodwork plans to make sure that we support pandas 1.3.0. Here is the pull request in progress
  - https://github.com/alteryx/woodwork/pull/987

**Comment by chukarsten** [comment]
EvalML 0.27.0 is incompatible as-is with Pandas 1.3.0rc1.  Will be working on an update to identify and fix some minor bugs introduced.

One potential incompatibility might be in XGBoost's use of DMatrix() applied to the new pandas DataFrame.  When the dataframe is handed to the DMatrix constructor with the columns attribute being a RangeIndex object rather than a list of int64, an exception is raised.
