### ISSUE TITLE
restaurant.csv validation score negative

### ISSUE THREAD

**Issue by chukarsten** [alteryx/evalml#2628]
The regression dataset `restaurant.csv` has a validation score that is negative.  It has been since the 0.30.0 release (-.017) and has become less negative in the upcoming 0.30.1 release (-.003).  We should probably figure out why this is happening!

![image](https://user-images.githubusercontent.com/64713315/129388415-66e68efd-d142-4612-b221-45692a6f6491.png)

**Comment by eccabay** [comment]
Upon first glance, the poor performance on this dataset is due to its tiny size and the curse of dimensionality: There are 137 rows total, and the performance tests use a train/test split of 50%, giving 68 total data points for training and 69 points for validation. On top of that, the dataset has 42 features.

According to [Wikipedia](https://en.wikipedia.org/wiki/Curse_of_dimensionality#Machine_Learning), "A typical rule of thumb is that there should be at least 5 training examples for each dimension in the representation.". Meaning in this case, we should have closer to 200+ data points to train with, at minimum. 

This explains the dataset's poor performance in general, but I'm going to start looking into why performance has changed so noticeably over the past few releases in particular.

**Comment by eccabay** [comment]
Much detective work behind me, there are two separate (but slightly related) reasons for the different changes with this dataset we've seen:
1. The improvement from -0.017137 in v0.30.0 -> -0.003936 in v0.30.1:
This change is actually just an illusion, there was no performance change between these releases. The difference showed up in the performance tests because the v0.30.0 test was run with `n_trials=5` while the v0.30.1 test was run with `n_trials=2`. If you look at the performance tests comparing v0.30.2 and v0.31.0, you see both values are back down to -0.017137. The trials matter since we change the random seed over each trial, and that is enough to make a noticeable performance difference with such a tiny dataset.

2. The regression from 0.005419 in v0.29.0 -> -0.017137 in v.0.30.0:
This change is not an illusion, it was introduced by merging in the `LogTransformer`. This dataset uses the `LogTransformer` in all its usual pipelines, but the performance degradation was missed because the performance tests for that PR were run with `n_trials=1`, meaning we only ran them with `random_state=0`. Coincidentally, when the random state is 0 for this dataset, the best performing pipeline is actually the `Mean Baseline Regression Pipeline`, which doesn't use the `LogTransformer` and therefore didn't experience regression.

**Comment by eccabay** [comment]
Moving forward, steps I think should be taken to prevent this sort of issue from coming up again:
- To improve performance with this sort of too small, too highly-dimensioned dataset, resolve #2747 
- To prevent confusion/missed information when running performance tests, we should increase the significance of the `n_trials` argument:
    - Add `n_trials` to the looking glass `get_metadata` function (this way it becomes visible when generating reports)
    - Increase the default number of trials to at least 2, but maybe even all the way to 5, since that's how we run our release perf tests anyways.
Will file an issue to track the looking glass changes.
