### ISSUE TITLE
TypeError warning about PipelineBaseMeta

### ISSUE THREAD

**Issue by dsherry** [alteryx/evalml#2788]
Repro: run automl on `city_rev.csv`
```
TypeError using the default encoder: Object of type PipelineBaseMeta is not JSON serializable; Will use string representation instead.
```
[Cloudwatch link](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Fecs$252Fevalml-test/log-events/ecs$252Fprod-evalml$252F9da7d5e7ccc44ca6a2fdd9c3943d1997)

**Comment by eccabay** [comment]
The issue comes from looking glass attempting to serialize the `"pipeline_class"` part of the full pipeline results. There are two solutions:
1. Update what evalml saves to the `"pipeline_class"` value to something serializable (for example, a string representation of the class instead of the class itself).
2. Add a case for encoding the pipeline class values in the looking glass encoder, which already handles serializing other non-primitive types.

I believe it's much simpler to update the looking glass code, since that has the added benefit of maintaining current behavior for evalml.
