### ISSUE TITLE
DataCheckActions user guide formatting

### ISSUE THREAD

**Issue by chukarsten** [alteryx/evalml#3000]
Attached is a picture of https://evalml.alteryx.com/en/latest/user_guide/data_actions.html.  We should probably either fix the formatting here by figuring out how to maybe get the offending index list to ellipsis (which seems difficult given that I think it's an underlying python native list in a python dictionary), or figure out a new way to deal with this.  It makes the user guide a little unwieldy!

![image](https://user-images.githubusercontent.com/64713315/139883615-20a3b72d-968f-4669-89f5-0b7649fa4462.png)

**Comment by angela97lin** [comment]
@chukarsten There are at least two things we could do:
1. Remove "null_row_indices" from the output of the data check.
2. Find a way to format this properly. We could simply not print out the output that's producing this long string. Calling print(...) for the statement rather than just having jupyter run it produces a more condensed output but still one that's unwieldy:
![image](https://user-images.githubusercontent.com/5422235/139923601-9e6806b7-52c6-4b21-8911-10cd1cd7ef6f.png)


Thoughts? I think I like option 1 better, unless we feel a need to store this info somewhere, for cases just like this!

If we have a large dataset and the highly null check triggers, it'll always print out a long list of indices!

**Comment by freddyaboulton** [comment]
I vote 1 too but I think we added it for data health? @ParthivNaresh might now. I don't think the data health _should_ need all these indices though so maybe we can refactor?

**Comment by ParthivNaresh** [comment]
Data health does need this for the final payload. Maybe we could add this into a static method which could be called separately by data health but won't be necessary for the data checks here?
