### ISSUE TITLE
Permutation importance fails on some objectives when target is categorical

### ISSUE THREAD

**Issue by eccabay** [alteryx/evalml#3012]
Repro:
```
import pandas as pd
from evalml.model_understanding import calculate_permutation_importance
from evalml.pipelines import BinaryClassificationPipeline

X = pd.DataFrame({'a': range(100)})
y = pd.Series(["Yes" if i%2==0 else "No" for i in range(100)])

component_graph = [
        "Imputer",
        "One Hot Encoder",
        "Elastic Net Classifier",
    ]
pipeline = BinaryClassificationPipeline(component_graph)
pipeline.fit(X, y)

permutation_importance = calculate_permutation_importance(
        pipeline, X, y, 'precision'
)
```

Also fails for accuracy, F1, and others. Does not fail for log loss, I'm not sure why. Discovered while trying to generate `readable_explanation` examples.

**Comment by freddyaboulton** [comment]
Nice find! 

Two thoughts:
1. The pipeline in the repro should have a label encoder since the targets are strings.
2. Interestingly the `slow` method does not produce an error

```python
calculate_permutation_importance_one_column(
        pipeline, X, y, "a", "f1", fast=False
)
```

I think what's happening is that in the fast method, we call `inverse_transform` after `estimator.predict` [here](https://github.com/alteryx/evalml/blob/main/evalml/model_understanding/permutation_importance.py#L327).

This was done because in regression problems where there is a target transformer, say LogTransformer, you want the predictions and targets to be in the original scale so that the permutation importance are in the original units of the problem. However, the problem for classification problems is that we actually don't want the targets or predictions in the original "unencoded" state because our sklearn objectives expect 0, 1 values.

Maybe what we can do is move this [classification check](https://github.com/alteryx/evalml/blob/main/evalml/model_understanding/permutation_importance.py#L153) into `_fast_scorer` and make sure the following behavior is met:
1. If classification, do not call inverse_transform, make sure the target variable is encoded. 
2. If regression, always call inverse target.
