### ISSUE TITLE
Refactor ARIMA/Prophet to use only use date_index parameter

### ISSUE THREAD

**Issue by freddyaboulton** [alteryx/evalml#3046]
Our ARIMA/Prophet components were originally designed to work with an optional `date_index` parameter. Now that the date_index is required in #3041, we should refactor our components in light of this.

For example, we can simplify the logic in `_get_dates`:

```python
    def _get_dates(self, X, y):
        date_col = None
        if y is not None:
            y_index_type = infer_feature_types(
                pd.Series(y.index)
            ).ww.logical_type.type_string
            if y_index_type == "datetime":
                date_col = y.index
        if X is not None:
            X_index_type = infer_feature_types(
                pd.Series(X.index)
            ).ww.logical_type.type_string
            if self.parameters["date_index"] in X.columns:
                date_col = X.pop(self.parameters["date_index"])
            elif X_index_type == "datetime":
                date_col = X.index
        if date_col is None:
            msg = (
                "ARIMA regressor requires input data X to have a datetime column specified by the 'date_index' parameter. "
                "If not it will look for the datetime column in the index of X or y."
            )
            raise ValueError(msg)
        return date_col, X
```

**Comment by ParthivNaresh** [comment]
`date_index` being a required parameter changes how we approach this for AutoML, but for OS users who want to call ARIMA/Prophet directly, we still have to take into consideration that they might choose to pass data that has datetime information in the index instead of as a column.

I'd say these are the two options:
1. Not support datetime information in the index for OS users who want to access the estimators directly.
2. Continue to support users who might pass in datetime information in the index, but make the necessary refactor to support the fact that `date_index` is a mandatory when using AutoML.

**Comment by freddyaboulton** [comment]
Can we require users pass in a non-None `date_index` parameter that corresponds to a column in `X` ? I think it's ok to ask users to change their data to meet our requirements if they're trying to use our components directly, like how prophet requires `ds` and `y` columns.
