### ISSUE TITLE
Use one sampler for split preprocessing pipeline

### ISSUE THREAD

**Issue by jeremyliweishih** [alteryx/evalml#3076]
In the split preprocessing pipelines introduced by #2986 each preprocessing chain contains a sampler as each chain is generated by `make_pipeline()` and currently the y output to the final estimator is taken from the categorical chain's sampler. This might be an issue as oversampling is handled differently for categorical and numeric data as detailed in this conversation. This issue tracks investigating the effects of choosing the categorical sampler and ensuring there is no performance lost from doing so.

**Comment by jeremyliweishih** [comment]
@freddyaboulton this tracked the double sampler issue but not sure why I closed this. I can open this up to track double sampler but a more generalized issue might be better as its touching multiple projects.

**Comment by freddyaboulton** [comment]
@jeremyliweishih Thank you for reopening ! I've renamed it to be more general and also linking with #2997 which I think is the root cause of these kinds of issues.

**Comment by freddyaboulton** [comment]
We should prioritize this as I think there may be some performance implications to this.

Repro

1. Comment out this line in `_create_fast_fina`
```python
    def _create_fast_final(self):
        estimators = [
            estimator
            for estimator in get_estimators(self.problem_type)
            #if estimator not in self._naive_estimators()
        ]
```
2. Run Automl search on the fraud dataset
```python
from evalml.automl import AutoMLSearch
from evalml.preprocessing import split_data
import pytest
from evalml.demos import load_fraud

X, y = load_fraud(1000)


X_train, _, y_train, _ = split_data(X, y, "binary", test_size=.5)

automl = AutoMLSearch(X, y, "binary", verbose=True, automl_algorithm="default")
automl.search()
```

You'll notice that the non-split RF pipeline does better than the split RF pipeline

### Non split
```
Random Forest Classifier w/ Label Encoder + DateTime Featurizer + Imputer + One Hot Encoder + Oversampler + RF Classifier Select From Model:
	Starting cross validation
	Finished cross validation - mean Log Loss Binary: 0.253
```

### Split
```
Random Forest Classifier w/ Label Encoder + Select Columns By Type Transformer + Label Encoder + DateTime Featurizer + Imputer + Oversampler + Select Columns Transformer + Select Columns Transformer + Label Encoder + Imputer + One Hot Encoder + Oversampler:
	Starting cross validation
	Finished cross validation - mean Log Loss Binary: 0.277
```

These two pipelines should perform the same right? One difference that comes to mind is that the non-split pipeline only has one oversampler. It could also be that the feature selector in the non-split case is selecting predictive features for every fold. In the split case, we select the ones for the third fold. 

AC:
1. Why do these pipelines score differently?
2. Have one sampler for split pipelines. Even if there isn't a score impact of having two samplers, I think we should only have one sampler. However, I can be convinced otherwise if someone can show there isn't a score impact or search time impact to having two samplers.
