### ISSUE TITLE
Add python 3.10 support

### ISSUE THREAD

**Issue by gsheni** [alteryx/evalml#3128]

**Comment by freddyaboulton** [comment]
The problem here is that some of our dependencies (sktime, prophet) don't even support 3.9 yet.

**Comment by chukarsten** [comment]
@freddyaboulton this is good to have filed though.  I'll just kick the can to late January and we can re-evaluate.

As of right now, it seems sktime doesn't even support Python 3.9: https://github.com/alan-turing-institute/sktime/issues/664 and neither does prophet.  I would add these 3.9 support issues as dependencies but I can't seem to since I'm not a maintainer in the other repos.
