### ISSUE TITLE
Use sphinx-autoapi to build API modules statically

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#601]
During the flurry of testing that happened to get the improved API objectives documentation build to succeed on ReadtheDocs, I came across the `sphinx-autoapi` extension from [RtD's suggestions on cutting build resources](https://docs.readthedocs.io/en/stable/guides/build-using-too-many-resources.html) (a good doc to come back to if we face this again!). As the documentation states:

**If you are installing a lot of Python dependencies just to document your Python modules API using sphinx.ext.autodoc, you can give a try to sphinx-autoapi Sphinx’s extension instead which should produce the exact same output but running statically. This could drastically reduce the memory and bandwidth required to build your docs.**

If we choose to pursue this, we may also want to check on all of the warnings about circular dependencies that the extension produces, as well as if it actually decreases our build time (https://readthedocs.com/projects/feature-labs-inc-evalml/builds/313458/ --> 600+ seconds isn't really an improvement, but this may be because I hadn't actually replaced our previous mechanism of using `autodoc` for building modules?)

**Comment by dsherry** [comment]
Goal: speed up RTD build

**Comment by freddyaboulton** [comment]
I started looking into this with this draft https://github.com/alteryx/evalml/pull/2458 but looks like the RTD build time is actually longer! [build](https://readthedocs.com/projects/feature-labs-inc-evalml/builds/666619/)

One possible reason is that we're still calling autodoc in addition to autoapi when we go build the api reference. 

Maybe someone who knows sphinx better than I do can help me look into this? autopi is maintained by RTD, maybe we can ask RTD for help?

**Comment by freddyaboulton** [comment]
Update: I was able to set it up correctly! The build is now about two minutes faster https://readthedocs.com/projects/feature-labs-inc-evalml/builds/667679/

Turns out autoapi is not a drop-in replacement for autodoc, it's an entirely different build system with its own quirks lol. As a result, our autodoc templates don't transition neatly to autoapi so the API reference looks different (I'd say worse?). You can check it out [here](https://feature-labs-inc-evalml--2458.com.readthedocs.build/en/2458/autoapi/index.html).

The autoapi docs do say that they have their own templates, but we need to decide if it's worth investing the time.
