### ISSUE TITLE
Data check to detect multicollinearity

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#811]
Following the Data Checks API project, all pre-existing guardrails, including `detect_label_leakage` were converted to use the new Data Checks API (now `DetectLabelLeakageDataCheck`). However, that data check only works for numerical columns.

Some previous work had been done with #184 and #141 as guardrails. It would be useful to use what was started in those PRs and add data checks to address correlation / multilinearity for categorical columns.

Older relevant issues / PRs:
https://github.com/FeatureLabs/evalml/issues/26

**Comment by rpeck** [comment]
Some notes from my previous discussions:

### Why do we care?

1. Unless you're using a model algorithm like GLM with Lasso, that does feature selection via regularization, your model will generally use all the correlated features in varying degrees. That means that feature importance cannot be trusted, because the contribution of a single "conceptual feature" is split across all of the features in a group, making them look unimportant. When a customer tries to explain a prediction (e.g., why someone's credit was denied) the explanation won't be correct.

1. When customers compare the important features among a set of pipelines they can see what looks like totally different features used by each pipeline. This makes them confused and reduces trust in the system.

1. When customers re-train with a fresh set of data they will again see a different set of important features.

**Comment by rpeck** [comment]
### Landmines

1. The traditional "stats 101" way of finding correlated features, "matrix math style", will blow up on large column counts, as Dylan pointed out. The correlation matrix in PS will have this problem, although I guess we hit other limitations first right now. :-)

It occurred to me a few years ago that it should be possible to take an agglomerative approach by decomposing the table into several iterations of groups of, say, 1000 columns, doing correlation matrices of all of these groups with a limited number of rows, and then combining their clusters. Once the potential clusters are identified you could then do true correlation matrices for the column groups in each cluster.

There might be other ways of getting where we want to go for this use case, too...

1. As Dylan pointed out: for some datasets there might be significant signal differences between features that are even correlated 0.95.

Where I've seen this is in unbalanced classification problems or ones in which different features have different predictive power for different categorical levels. Imagine for example a medical dataset in which two different test results are highly correlated with each other, but one of them is highly predictive for males and the other for females. The same kind of thing can happen with _interactions_ (differences in how similar-looking features interact with other features).

We'd want to be careful about surfacing these issues.

1. Like with feature selection we also need to be careful about sparsity. <flesh this thought out later :-) >
