### ISSUE TITLE
AutoML: apply nonlinear transformation to regression target during search

### ISSUE THREAD

**Issue by angela97lin** [alteryx/evalml#914]
https://scikit-learn.org/stable/auto_examples/compose/plot_transformed_target.html#sphx-glr-auto-examples-compose-plot-transformed-target-py

Could be useful to further affirm that this is useful and improves the accuracy of our models first!

**Comment by dsherry** [comment]
This came up recently in conversation. This dataset has a great example of a long-tail distribution for regression. Because we don't give users the ability to remove outliers or to log-transform the target, automl collapses on this dataset!

My hope is that we can define three data check actions for when we detect outliers on a dataset, or detect long-tail data:
1. Apply log transform during training (default)
2. Drop outliers
3. Do nothing

This issue tracks building a component which applies a log-transform during model training. This is similar to our undersampler/oversampler components which only operate during training, and are no-ops when we compute predictions outside of training.

**Comment by dsherry** [comment]
Hey @ParthivNaresh leaving a note here for us to discuss later: we should make our transform be robust to scale and offset. So if the target has 0s or negative values, we could first shift it before applying the log transform.

**Comment by ParthivNaresh** [comment]
> Hey @ParthivNaresh leaving a note here for us to discuss later, which @rpeck brought up: we should make our transform be robust to scale and offset. So if the target has 0s or negative values, we could first shift it before applying the log transform.

@dsherry Indeed, I added `y_new = y + abs(y.min()) + 1` to create an all positive distribution for this reason. Let me know if there's perhaps a better way we can approach it.
